namespace SistemasdeTarefas.Models
{
    public class CustomerInvoice
    {
        public int Id { get; set; }
        public int IdInvoice { get; set; }
        public int DocYear { get; set; }
        public int IdCustomer { get; set; }
        public int IdAvaiableDocSeries { get; set; }
        public string? DocNo { get; set; }
        public string? ReasonRectification { get; set; }
        public bool Regularizado { get; set; }
        public decimal SaldoDisponivel { get; set; }
        public int IdAluno { get; set; }
        public string? NomeAluno { get; set; }
        public int NumAluno { get; set; }
        public string? Ciclo { get; set; }
        public string? Classe { get; set; }
        public string? Turma { get; set; }
        public string? Turno { get; set; }
        public string? Curso { get; set; }
        public int IdAno { get; set; }
        public int Ano { get; set; }
        public int IdMatricula { get; set; }
        public string? NumMatricula { get; set; }
        public string? ApiId { get; set; }
        public bool AppSync { get; set; }
        public string? RefMultiCx { get; set; }
        public int TypeEntity { get; set; }
        public DateTime DocDate { get; set; }
        public string? Name { get; set; }
        public string? Nif { get; set; }
        public string? CurrencyCode { get; set; }
        public int IdCurrency { get; set; }
        public string? DocStatus { get; set; }
        public DateTime DocStatusDate { get; set; }
        public string? ReasonChange { get; set; }
        public string? SourceId { get; set; }
        public string? SourceBilling { get; set; }
        public string? SerieType { get; set; }
        public string? SerieId { get; set; }
        public int IdDocTypeConfig { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal? CreditAmount { get; set; }
        public decimal ExchangeRate { get; set; }
        public bool SelfBillingIndicator { get; set; }
        public bool CashVats { get; set; }
        public bool ThirdPartySBI { get; set; }
        public int? IdTaxExemption { get; set; }
        public string? TaxExemptionCode { get; set; }
        public string? TaxExemptionDescription { get; set; }
        public decimal TaxPayable { get; set; }
        public decimal NetTotal { get; set; }
        public decimal GrossTotal { get; set; }
        public string? Hash { get; set; }
        public string? HashControl { get; set; }
        public string? TransactionId { get; set; }
        public string? ShipTo_DeliveryID { get; set; }
        public DateTime ShipTo_DeliveryDate { get; set; }
        public string? ShipTo_WarehouseID { get; set; }
        public string? ShipTo_LocationID { get; set; }
        public string? ShipFrom_DeliveryID { get; set; }
        public DateTime ShipFrom_DeliveryDate { get; set; }
        public string? ShipFrom_WarehouseID { get; set; }
        public string? ShipFrom_LocationID { get; set; }
        public decimal TxDiscountFin { get; set; }
        public decimal DiscountAmountFin { get; set; }
        public int? IdModPag { get; set; }
        public bool UsouSaldo { get; set; }
        public decimal ValorSaldoUsado { get; set; }
        public DateTime? DataModPag { get; set; }
        public string? NumModPag { get; set; }
        public int? IdContaTs { get; set; }
        public bool IsCreditado { get; set; }
        public string? NrTalaoPag { get; set; }
        public bool Anulado { get; set; }
        public int? IdEstadoAnulacao { get; set; }
        public int? IdUserPedeAnulac { get; set; }
        public DateTime? DataPedeAnulac { get; set; }
        public string? HoraPedeAnulac { get; set; }
        public int? IdUserAprovAnulac { get; set; }
        public DateTime? DataAprovAnulac { get; set; }
        public string? HoraAprovAnulac { get; set; }
        public int? IdDocOriginal { get; set; }
        public bool Printed { get; set; }
        public string? NomeEmpresa { get; set; }
        public string? DesignSocialEmpresa { get; set; }
        public string? MoradaEmpresa { get; set; }
        public string? BairroEmpresa { get; set; }
        public string? MunicipioEmpresa { get; set; }
        public string? NifEmpresa { get; set; }
        public string? EmailEmpresa { get; set; }
        public string? WebSiteEmpresa { get; set; }
        public string? TelefEmpresa { get; set; }
        public string? FaxEmpresa { get; set; }
        public decimal CapSocialEmpresa { get; set; }
        public string? Observacoes { get; set; }
        public string? BuildingNumber { get; set; }
        public string? StreetName { get; set; }
        public string AdressDetail { get; set; }
        public string City { get; set; }
        public string? PostalCode { get; set; }
        public string? Province { get; set; }
        public string? Bairro { get; set; }
        public string CountryCode { get; set; }
        public int IdCountry { get; set; }
        public DateTime? DateAdd { get; set; }
        public DateTime? DateChange { get; set; }
        public string? TimeAdd { get; set; }
        public string? TimeChange { get; set; }
        public int? IdUserAdd { get; set; }
        public int? IdUserChange { get; set; }
        public DateTime? DateDeleted { get; set; }
        public int? IdUserDel { get; set; }
        public bool Deleted { get; set; }
        public string? TimeDeleted { get; set; }
        public int? Country_Id { get; set; }
        public int? Currency_Id { get; set; }
        public int? Customer_Id { get; set; }
        public int? TaxExemption_Id { get; set; }
        public decimal TotalIliquido { get; set; }
        public decimal IncidenciaItemsSemIva { get; set; }
        public decimal IncidenciaItemsComIva { get; set; }
        public string? ExtensoDoTotal { get; set; }
        public bool JaImprimiu { get; set; }
        public int? IdUserPrintOrig { get; set; }
        public string? TimePrintOrig { get; set; }
        public DateTime? DatePrintOrig { get; set; }
        public int? IdUserRePrint { get; set; }
        public string? TimeRePrint { get; set; }
        public DateTime? DateRePrint { get; set; }
        public int TipoDescFinanc { get; set; }
        public string? AnoLectivo { get; set; }
        public string? EntidadeMultiCx { get; set; }
        public bool GerouRefMultiCx { get; set; }
        public int StatusRefMultiCx { get; set; }
        public DateTime? DataPagRefMCx { get; set; }
        public bool FromAutoFact { get; set; }
        public bool IsCredForAD { get; set; }
        public DateTime? ValidadeRefMCx { get; set; }
    }

}
